### ISSUE TITLE
Al registrar un usuario me dice que el username está repetido

### ISSUE THREAD

**Issue by dmarcob** [STW-Enjoyers/backend#29]
Buenas, estaba probando a registrar un usuario y el backend me devuelve 422 con el mensaje "Duplicate username found". Me he asegurado que el username nunca lo hemos registrado. Adjunto foto:
![Captura de pantalla de 2022-05-03 11-04-57](https://user-images.githubusercontent.com/45805074/166428974-1da2bde2-52a3-4e9e-9d93-2b5caad74297.png)

Inmediatamente después he pensado, pues le añado un caracter más al final del username y listo. Pues no XD, el backend ha devuelto un 422 con el mensaje "Duplicate email address found". Adjunto foto:

![Captura de pantalla de 2022-05-03 11-05-17](https://user-images.githubusercontent.com/45805074/166429947-ed23374c-5d93-4097-ab7f-f4e6c2acb4c6.png)

No se que puede estar ocurriendo, muchas gracias chicos :)

**Comment by dolansete** [comment]
Altoke mi rey

**Comment by dolansete** [comment]
Pongo un poco lo que pasaba, para los baneos hubo que refactorizar la forma en la que se guardaba el usuario, pero no se hizo del todo bien, ya que faltaba un else, que hacía que la contraseña se guardara sin encriptar, lo que impedía la autenticación. Por esto, se guardaba el usuario al registrar pero no devolvía el usuario, sino contraseña incorrecta, entonces pensando que ha fallado el register, el usuario volvía a registrarlo y le salía duplicate.
